In [2]:
from pathlib import Path

In [95]:
def load_tv_table_dict(tv_dir_path):

    tv_dir_path = Path(tv_dir_path)
    tv_table_dict =dict()
    for table_path in tv_dir_path.iterdir():
        table_name =table_path.name.split('.csv')[0]
        table = pd.read_csv(table_path).astype('category')
        table_ref = table_path.name.split('_')[0]
        table.columns = [table_ref+'_'+el if not el.startswith(table_ref) else el for el in table.columns ]
        table = table.rename(columns ={f'{table_ref}_id':f'{table_name}_id'})
        tv_table_dict[table_name] = table 
    for table_name,table in tv_table_dict.items():
        
        foreign_ids = [col for col in table if col.endswith('_id') and not col.startswith(table_name)]
        for foreign_id in foreign_ids:
            foreign_table=tv_table_dict[foreign_id.split('_id')[0]]
            table = table.merge(foreign_table,on = foreign_id,how='left')
        cols = [el for el in table if not any(s in el for s in ['simulateur','simu_ordre','id'])]
        cols.append(f'{table_name}_id')
        tv_table_dict[table_name] =table

    return tv_table_dict

def load_tr_table_dict(tr_dir_path):

    tr_dir_path = Path(tr_dir_path)
    tr_table_dict =dict()
    for table_path in tr_dir_path.iterdir():
        table_name =table_path.name.split('.csv')[0]
        table = pd.read_csv(table_path).astype('category')
        table = table.rename(columns ={'id':f'{table_name}_id'})
        tr_table_dict[table_name] =table

    return tr_table_dict

In [96]:
tv_dir_path =Path(r'D:\data\dpe_full\dpe_doc\tv_tables')
tr_dir_path =Path(r'D:\data\dpe_full\dpe_doc\tr_tables')

In [98]:
tv_dir_path = Path(tv_dir_path)
tv_table_dict =dict()
for table_path in tv_dir_path.iterdir():
    table_name =table_path.name.split('.csv')[0]
    table = pd.read_csv(table_path).astype('category')
    table_ref = table_path.name.split('_')[0]
    table.columns = [table_ref+'_'+el if not el.startswith(()) else el for el in table.columns ]
    table = table.rename(columns ={f'{table_ref}_id':f'{table_name}_id'})
    tv_table_dict[table_name] = table 
for table_name,table in tv_table_dict.items():

    foreign_ids = [col for col in table if col.endswith('_id') and not col.startswith(table_name)]
    foreign_ids 
    for foreign_id in foreign_ids:
        foreign_table=tv_table_dict[foreign_id.split('_id')[0]]
        table = table.merge(foreign_table,on = foreign_id,how='left')
    cols = [el for el in table if not any(s in el for s in ['simulateur','simu_ordre','id'])]
    cols.append(f'{table_name}_id')
    tv_table_dict[table_name] =table

KeyError: 'tv003_tv017_zone_hiver'

In [107]:
'ab'.startswith('a|c')

False

In [105]:
tv_table_dict['tv017_zone_hiver']

,tv017_zone_hiver_id,tv017_code,tv017_t_ext_moyen,tv017_peta_cw,tv017_dh14,tv017_prs1
0,1,H1,6.58,10.5,42030,3.6
1,2,H2,8.08,12.0,33300,3.4
2,3,H3,9.65,14.5,22200,2.9

In [102]:
table['tv017_zone_hiver']

KeyError: 'tv017_zone_hiver'

In [97]:
tv_table_dict = load_tv_table_dict(tv_dir_path)
tr_table_dict = load_tv_table_dict(tr_dir_path)

KeyError: 'tv003_tv017_zone_hiver'

In [79]:
table_name ='tv009_coefficient_transmission_thermique_vitrage'

SyntaxError: invalid syntax (<ipython-input-91-e0aedc9d569f>, line 1)

In [64]:
for _id in foreign_ids:
    foreign_table=tv_table_dict[_id]

KeyError: 'tv009_ug_type_vitrage_id'

In [26]:

class Singleton(type):
    _instances = {}
    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]

class DPEMetaData(metaclass=Singleton):

    def __init__(self ,assets_dir=Path(r'D:\data\dpe_full\dpe_doc')):

        self.tv_table_dict = load_tv_table_dict(assets_dir/'tv_tables')
        self.tr_table_dict = load_tr_table_dict(assets_dir/'tr_tables')


    def merge_all_tr_table(self, table):
        table = table.copy()
        tr_cols = [col for col in table.columns if col.startswith('tr')]
        for tr_col in tr_cols:
            table = self.merge_tr_table(table, tr_col)
        return table

    def merge_tr_table(self, table, tr_col):
        tr_name = tr_col.split('_')[0].lower()
        tr_table = self.tr_table_dict[tr_name]
        tr_table = tr_table.rename(columns={'code': tr_col})
        table[tr_col] = ((tr_name + '_' + table[tr_col].fillna(pd.NA).astype(str).str.zfill(3)).str.upper()).astype('category')
        tr_code = tr_col.split('_')[0]
        cols = tr_table.columns.tolist()
        cols[0] = tr_col
        cols[1:] = [tr_code + '_' + col for col in cols[1:]]
        tr_table.columns = cols
        table = table.merge(tr_table, on=tr_col, how='left')
        table[cols]=table[cols].astype('category')
        table.index = table.index.astype(str)

        return table

    def merge_all_tv_table(self, table):
        table = table.copy()
        tv_cols = [col for col in table.columns if col.startswith('tv')]
        for tv_col in tv_cols:
            table = self.merge_tv_table(table, tv_col)
        return table

    def merge_tv_table(self, table, tv_col):
        tv_name = tv_col.split('_')[0].lower()
        tv_table = self.tv_table_dict[tv_name]
        tv_table = tv_table.rename(columns={'code': tv_col})
        tv_code = tv_col.split('_')[0]
        table[tv_col] = ((tv_name + '_' + table[tv_col].astype('string').str.zfill(3)).str.upper()).astype('category')
        cols = tv_table.columns.tolist()
        cols[0] = tv_col
        cols[1:] = [tv_code + '_' + col for col in cols[1:]]
        tv_table.columns = cols
        table = table.merge(tv_table, on=tv_col, how='left')
        table[cols]=table[cols].astype('category')
        table.index = table.index.astype(str)
        return table

In [23]:
td007

,id,td006_batiment_id,tr014_type_parois_opaque_id,reference,deperdition_thermique,tv001_coefficient_reduction_deperditions_id,tv002_local_non_chauffe_id,coefficient_transmission_thermique_paroi,coefficient_transmission_thermique_paroi_non_isolee,tv003_umur_id,tv004_umur0_id,tv005_upb_id,tv006_upb0_id,tv007_uph_id,tv008_uph0_id,resistance_thermique_isolation,epaisseur_isolation,surface_paroi
0,1048,209,1,Mur,40.27,1,NaN,0.35,0.00,NaN,78,NaN,NaN,NaN,NaN,0.00,10.00,115.06
1,1049,209,1,Mur,3.59,NaN,1,0.35,0.00,NaN,78,NaN,NaN,NaN,NaN,0.00,10.00,10.80
2,1050,209,4,Plafond,6.49,NaN,5,0.14,0.00,NaN,NaN,NaN,NaN,NaN,10,0.00,27.00,49.10
3,1814,364,1,Mur,31.71,1,NaN,0.38,0.00,1,78,NaN,NaN,NaN,NaN,0.00,9.00,82.67
4,1815,364,1,Mur,3.89,NaN,1,0.32,0.00,1,1,NaN,NaN,NaN,NaN,0.00,0.00,12.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439933,24115581,5419822,3,Plancher,17.35,261,NaN,0.25,0.00,NaN,NaN,85,9,NaN,NaN,0.00,0.00,69.40
439934,24115582,5419822,1,Mur,45.94,1,NaN,0.40,0.00,51,78,NaN,NaN,NaN,NaN,0.00,10.00,114.86
439935,24115588,5419822,1,Mur,5.60,NaN,1,0.40,0.00,51,69,NaN,NaN,NaN,NaN,0.00,0.00,17.50
439936,24115589,5419822,4,Plafond,9.33,1,NaN,0.23,0.00,NaN,NaN,NaN,NaN,99,10,0.00,0.00,40.55
439937,24115590,5419822,4,Plafond,6.22,NaN,5,0.23,0.00,NaN,NaN,NaN,NaN,99,10,0.00,0.00,38.65

In [7]:
import pandas as pd
import json
import requests
from pathlib import Path
import numpy as np
import sys
import requests
import json
from matplotlib import pyplot as plt
import seaborn as sns
sns.set_context('talk')
%matplotlib inline
if sys.platform =='linux':
    path_d = Path('/mnt/d')
else:
    path_d = Path('D://')
data_dir = path_d/'data'/'dpe_full'   

plot_dir = Path('.')/'plot'
plot_dir.mkdir(exist_ok=True,parents=True)

In [22]:
td007 =pd.read_csv(data_dir/'depts'/dept/'td007_paroi_opaque.csv',dtype=str)
td006 =pd.read_csv(data_dir/'depts'/dept/'td006_batiment.csv',dtype=str)
td001 =pd.read_csv(data_dir/'depts'/dept/'td001_dpe.csv',dtype=str)
td008 =pd.read_csv(data_dir/'depts'/dept/'td008_baie.csv',dtype=str)

In [8]:
dept = '38'
td011 =pd.read_csv(data_dir/'depts'/dept/'td011_installation_chauffage.csv',dtype=str)
td012 =pd.read_csv(data_dir/'depts'/dept/'td012_generateur_chauffage.csv',dtype=str)
td013 =pd.read_csv(data_dir/'depts'/dept/'td013_installation_ecs.csv',dtype=str)
td014 =pd.read_csv(data_dir/'depts'/dept/'td014_generateur_ecs.csv',dtype=str)
td006 =pd.read_csv(data_dir/'depts'/dept/'td006_batiment.csv',dtype=str)
td001 =pd.read_csv(data_dir/'depts'/dept/'td001_dpe.csv',dtype=str)
td005 =pd.read_csv(data_dir/'depts'/dept/'td005_fiche_technique.csv',dtype=str)

In [9]:
td011.columns

Index(['id', 'td006_batiment_id', 'tr003_type_installation_chauffage_id',
       'surface_chauffee', 'nombre_appartements_echantillon',
       'surface_habitable_echantillon', 'tv025_intermittence_id'],
      dtype='object')